// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArI3umJzaQDnRGj4mhs9CeKSsHs6OgZrY',
    appId: '1:939457999478:web:105b05335c821029576557',
    messagingSenderId: '939457999478',
    projectId: 'namma-workers',
    authDomain: 'namma-workers.firebaseapp.com',
    storageBucket: 'namma-workers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Lx6Ickm8MnbOyi4aSvmjfIX2cp-C2Uw',
    appId: '1:939457999478:android:0fb06ff8f9330099576557',
    messagingSenderId: '939457999478',
    projectId: 'namma-workers',
    storageBucket: 'namma-workers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRo63LWJQ_o6zOvj3zZR9kFFm3sE3tsD0',
    appId: '1:939457999478:ios:e0306792da052573576557',
    messagingSenderId: '939457999478',
    projectId: 'namma-workers',
    storageBucket: 'namma-workers.firebasestorage.app',
    iosBundleId: 'com.example.nammaWorkers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRo63LWJQ_o6zOvj3zZR9kFFm3sE3tsD0',
    appId: '1:939457999478:ios:e0306792da052573576557',
    messagingSenderId: '939457999478',
    projectId: 'namma-workers',
    storageBucket: 'namma-workers.firebasestorage.app',
    iosBundleId: 'com.example.nammaWorkers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArI3umJzaQDnRGj4mhs9CeKSsHs6OgZrY',
    appId: '1:939457999478:web:4e32162e1f1a9c3c576557',
    messagingSenderId: '939457999478',
    projectId: 'namma-workers',
    authDomain: 'namma-workers.firebaseapp.com',
    storageBucket: 'namma-workers.firebasestorage.app',
  );
}
